import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

 export const products = [
  {
    _id: uuid(),
    title: "Wooden Puzzle Toy for Vegetables Identification with Cute Picture for Kids. First Learning Toy. ",
    price: "349",
    discount: "22% off",
    sellingPrice: "447",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod1.jpg",
  },
  {
    _id: uuid(),
    title: "India Map Wooden Puzzle, State wise Cut, Easy to Hold knobs, Beautiful Illustration with Major Attractions.",
    price: "449",
    discount: "18% off",
    sellingPrice: "547",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod2.jpg",
  },
  {
    _id: uuid(),
    title: "Quizine: India Map Poster Activity Kit. Have Fun answering The Questions with Stickers on India's Poster! ",
    price: "499",
    discount: "23% off",
    minAge: "4 years",
    maxAge: "above",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod3.jpg",
  },
  {
    _id: uuid(),
    title: 'Solar System Puzzle, 60 Pc, 12"x18", Age 4+, Designed and Made in India. The Best Floor Puzzles for Your Kids! ',
    price: "499",
    discount: "9% off",
    minAge: "4 years",
    maxAge: "above",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod4.jpg",
  },
  {
    _id: uuid(),
    title: "Number Recognition Wooden Puzzle with Pictures to Promote Early Learning and Improve Motor Skills and Memory for Kids.",
    price: "449",
    discount: "25% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod5.jpg",
  },
  {
    _id: uuid(),
    title: 'World System Puzzle, 60 Pc, 12"x18", Age 4+, Designed and Made in India. The Best Floor Puzzles for Your Kids!  ',
    price: "499",
    discount: "23% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Puzzles",
    imgUrl: "/assets/productImages/prod6.jpg",
  },
  {
    _id: uuid(),
    title: "Winter Wondersticks DIY Kit with 15 Inch Honeycomb and Coaster, Ice- Cream Sticks, Patterned Seasons Greeting Cards 2021. ",
    price: "499",
    discount: "17% off",
    minAge: "4 years",
    maxAge: "above",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest1.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set Animal Theme DIY Rakhi making kit with a Rs. 200 worth Gift Box! Contains Rakhi, Greeting card, a Gift set for...",
    price: "449",
    discount: "25% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest1.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set Frozen Theme DIY rakhi making kit a Rs. 200 worth Gift Box! Contains Rakhi, Greeting card a Gift set for...",   
    price: "499",
    discount: "17% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest2.jpg",
  },
  {
    _id: uuid(),
    title: "My Christmas Decoration DIY Coloring and Craft Kit with MDF Christmas Tree Set, Decorative Christmas Ornaments. Alongwith 15 inch Honeycomb Tree and Coaster. ",
    price: "649",
    discount: "19% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest3.jpg",
  },
  {
    _id: uuid(),
    title: "My India MDF Coloring Kit, Republic and Independence Special DIY.Set of India Map, National Flag, National Emblem with Colors, Pompom, Silver, Golden Beads and Brush",    
    price: "599",
    discount: "14% off",
    minAge: "3 years",
    maxAge: "10 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest4.jpg",
  },
  {
    _id: uuid(),
    title: "My Christmas Decorations DIY Coloring and Craft Kit with MDF Christmas Tree Set, Christmas Ornaments, Santa Post Card, 12 Color Set and Decorative Materials.",   
    price: "599",
    discount: "14% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest5.jpg",
  },
  {
    _id: uuid(),
    title: "My India Decor Kit, 4 Caps, 4Tricolor Band, 2 Eye Mask, Tri-Color Balloons, Crepe Paper to Make hangings, Kite Frills for Decoration ",
    price: "499",
    discount: "17% off",
    minAge: "4 years",
    maxAge: "above",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest6.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set God Theme DIY rakhi making kit with a Rs. 200 worth Gift Box. Contains Rakhi Greeting card and a Gift set for...",    
    price: "499",
    discount: "17% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest7.jpg",
  },
  {
    _id: uuid(),
    title: "3D Janmashtami DIY Kit- Kanhaiya ka Jhoola, Easy to Assemble and Decorate Krishna's Favourite Place with This kit. ",    
    price: "499",
    discount: "14% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest8.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set Animal Theme DIY Rakhi making kit with a Rs. 200 worth Gift Box! Contains Rakhi, Greeting card and a Gift set for...",    
    price: "449",
    discount: "25% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest9.jpg",
  },
  {
    _id: uuid(),
    title: "Ganpati Idol Mosaic Kit- DIY Craft for Kids Above Age 4. Prepare a Beautiful Ganesha Idol with The Best Engaging Activity for The Festive Season. ",    
    price: "499",
    discount: "17% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest10.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set Superhero Theme DIY rakhi making kit a Rs. 200 worth Gift Box by BlackMole!! Contains Rakhi, Greeting card and a Gift set for...",   
    price: "499",
    discount: "17% off",
    minAge: "2 years",
    maxAge: "6 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest11.jpg",
  },
  {
    _id: uuid(),
    title: "BadgeIT: India DIY Kit (Set of 5) Foam Cut Outs, Circle, Champion & India Shaped. Includes Colors, Magnets, Transparent Stickers ",   
    price: "499",
    discount: "29% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest12.jpg",
  },
  {
    _id: uuid(),
    title: "5-Set Flower Theme DIY rakhi making kit with a Rs. 200 worth Gift Box by BlackMole!! Contains Rakhi, Greeting card and a Gift set for...",    
    price: "499",
    discount: "17% off",
    minAge: "2 years",
    maxAge: "5 years",
    categoryName: "Creative",
    imgUrl: "/assets/productImages/fest13.jpg",
  },
 
];
